#ifndef RS_COMMANDS_H_
#define RS_COMMANDS_H_

/** RS_CMD_PREFIX can be defined with -D from the Makefile */
#ifndef RS_CMD_PREFIX
#define RS_CMD_PREFIX "FT"
#endif

#define RS_CREATE_CMD RS_CMD_PREFIX "_CREATE"
#define RS_ADD_CMD RS_CMD_PREFIX "_ADD"
#define RS_SAFEADD_CMD RS_CMD_PREFIX "_SAFEADD"
#define RS_SETPAYLOAD_CMD RS_CMD_PREFIX "_SETPAYLOAD"
#define RS_ADDHASH_CMD RS_CMD_PREFIX "_ADDHASH"
#define RS_SAFEADDHASH_CMD RS_CMD_PREFIX "_SAFEADDHASH"
#define RS_INFO_CMD RS_CMD_PREFIX "_INFO"
#define RS_SEARCH_CMD RS_CMD_PREFIX "_SEARCH"
#define RS_AGGREGATE_CMD RS_CMD_PREFIX "_AGGREGATE"

#define RS_EXPLAIN_CMD RS_CMD_PREFIX "_EXPLAIN"
#define RS_EXPLAINCLI_CMD RS_CMD_PREFIX "_EXPLAINCLI"
#define RS_DEL_CMD RS_CMD_PREFIX "_DEL"
#define RS_DROP_CMD RS_CMD_PREFIX "_DROP"
#define RS_GET_CMD RS_CMD_PREFIX "_GET"
#define RS_MGET_CMD RS_CMD_PREFIX "_MGET"
#define RS_TAGVALS_CMD RS_CMD_PREFIX "_TAGVALS"

#define RS_SUGADD_CMD RS_CMD_PREFIX "_SUGADD"
#define RS_SUGGET_CMD RS_CMD_PREFIX "_SUGGET"
#define RS_SUGDEL_CMD RS_CMD_PREFIX "_SUGDEL"
#define RS_SUGLEN_CMD RS_CMD_PREFIX "_SUGLEN"

#define RS_CURSOR_CMD RS_CMD_PREFIX "_CURSOR"

#define RS_SYNADD_CMD RS_CMD_PREFIX "_SYNADD"
#define RS_SYNUPDATE_CMD RS_CMD_PREFIX "_SYNUPDATE"
#define RS_SYNFORCEUPDATE_CMD RS_CMD_PREFIX "_SYNFORCEUPDATE"
#define RS_SYNDUMP_CMD RS_CMD_PREFIX "_SYNDUMP"

#define RS_ALTER_CMD RS_CMD_PREFIX "_ALTER"

#define RS_DEBUG RS_CMD_PREFIX "_DEBUG"

#define RS_SPELL_CHECK RS_CMD_PREFIX "_SPELLCHECK"

#define RS_DICT_ADD RS_CMD_PREFIX "_DICTADD"

#define RS_DICT_DEL RS_CMD_PREFIX "_DICTDEL"

#define RS_DICT_DUMP RS_CMD_PREFIX "_DICTDUMP"

#define RS_CONFIG RS_CMD_PREFIX "_CONFIG"
#endif
